name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: docker/cache-action@v2
        with:
          path: |
            ~/.cache/docker
            ~/.cache/buildx

      - name: Build Docker image
        run: |
          docker build -t python-server-demo .

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push Docker image
        run: |
          docker tag python-server-demo:latest 146225787475.dkr.ecr.us-east-1.amazonaws.com/python-server-demo:latest
          docker push 146225787475.dkr.ecr.us-east-1.amazonaws.com/python-server-demo:latest
